server:
  port: 8082

spring:
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**



mybatis-plus:
  typeAliasesPackage: com.qz.guns.modular.system.model

mybatis:
  mapper-locations: com.qz.guns.modular.system.dao.*.xml

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    db-name: guns





  #type-aliases-package: com.winter.model
